name: Bits 'n Bolts
markdown: redcarpet
highlighter: pygments
permalink: none
excerpt_seperator: <!--more-->
phone-number: +31 (0)628346915
email: thijs@bitsnbolts.nl
future: false
#baseurl: http://bitsnbolts.nl
title: Bits 'n Bolts
description: Bits 'n Bolts provides professional freelance Drupal development.
filepath: "/"
# filepath: http://files.bitsnbolts.nl/
environment: live
exclude: [node_modules]
